<?php

namespace Kemistra\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;





/**
 * StockMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockMaterielRepository extends EntityRepository
{
    
}
