<?php

namespace Kemistra\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeResultatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeResultatRepository extends EntityRepository
{
}
