<?php

namespace Kemistra\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;





/**
 * TypeAnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAnalyseRepository extends EntityRepository
{
    public function getDetails($id)
    {
        return $this->_em->createQueryBuilder()
                         ->from($this->_entityName, 'ta')->select('ta')
                         ->join('ta.typeResultats', 'tr')->addSelect('tr')
                         ->join('ta.utilise', 'u')->addSelect('u')
                         ->join('u.typeMateriel', 'tm')->addSelect('tm')
                         ->join('ta.typeConsommables', 'tc')->addSelect('tc')
                         ->where('ta.id = :id')
                         
                         ->setParameter('id', $id)
                         
                         
                         
                         ->getQuery()->getSingleResult();
    }
}
