jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Kemistra\MainBundle\Entity\Employe:
            algorithm:        sha256
            iterations:       1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:   { class: Kemistra\MainBundle\Entity\Employe, property: username }
        
        in_memory:
            memory:
                users:
                    kevin:  { password: keke, roles: [ 'ROLE_USER' ] }
                    responsable: { password: resp, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern:    ^/
            anonymous:  true
            provider:   main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: analyse
            logout:
                path:   logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
