homepage:
    pattern:  /
    defaults: { _controller: KemistraMainBundle:Default:index }

login:
    pattern:  /connexion
    defaults: { _controller: KemistraMainBundle:Default:login }

login_check:
    pattern:  /connexion-en-cours

logout:
    pattern:  /deconnexion





KemistraMainBundle_employe:
    resource: "@KemistraMainBundle/Resources/config/routing/employe.yml"
    prefix:   /gestion-des-employes

KemistraMainBundle_client:
    resource: "@KemistraMainBundle/Resources/config/routing/client.yml"
    prefix:   /gestion-des-clients

KemistraMainBundle_stockmateriel:
    resource: "@KemistraMainBundle/Resources/config/routing/stockmateriel.yml"
    prefix:   /gestion-du-stock-de-materiel

KemistraMainBundle_stockConsommable:
    resource: "@KemistraMainBundle/Resources/config/routing/stockconsommable.yml"
    prefix:   /gestion-du-stock-de-consommable

KemistraMainBundle_typeanalyse:
    resource: "@KemistraMainBundle/Resources/config/routing/typeanalyse.yml"
    prefix:   /analyses-realisables

KemistraMainBundle_analyse:
    resource: "@KemistraMainBundle/Resources/config/routing/analyse.yml"
    prefix:   /gestion-des-analyses


