analyse:
    pattern:  /
    defaults: { _controller: "KemistraMainBundle:Analyse:index" }

analyse_show:
    pattern:  /{id}/show
    defaults: { _controller: "KemistraMainBundle:Analyse:show" }

analyse_new:
    pattern:  /new
    defaults: { _controller: "KemistraMainBundle:Analyse:new" }

analyse_create:
    pattern:  /create
    defaults: { _controller: "KemistraMainBundle:Analyse:create" }
    requirements: { _method: post }

analyse_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KemistraMainBundle:Analyse:edit" }

analyse_update:
    pattern:  /{id}/update
    defaults: { _controller: "KemistraMainBundle:Analyse:update" }
    requirements: { _method: post|put }

analyse_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KemistraMainBundle:Analyse:delete" }
    requirements: { _method: post|delete }
