analyse:
    pattern:  /
    defaults: { _controller: "KemistraMainBundle:Analyse:index" }

analyse_show:
    pattern:  /{id}/details
    defaults: { _controller: "KemistraMainBundle:Analyse:show" }

analyse_new:
    pattern:  /nouvelle
    defaults: { _controller: "KemistraMainBundle:Analyse:new" }

analyse_create:
    pattern:  /creation
    defaults: { _controller: "KemistraMainBundle:Analyse:create" }
    requirements: { _method: post }

analyse_edit:
    pattern:  /{id}/edition
    defaults: { _controller: "KemistraMainBundle:Analyse:edit" }

analyse_update:
    pattern:  /{id}/mise-a-jour
    defaults: { _controller: "KemistraMainBundle:Analyse:update" }
    requirements: { _method: post|put }
