resultat:
    pattern:  /
    defaults: { _controller: "KemistraMainBundle:Resultat:index" }

resultat_show:
    pattern:  /{id}/show
    defaults: { _controller: "KemistraMainBundle:Resultat:show" }

resultat_new:
    pattern:  /new
    defaults: { _controller: "KemistraMainBundle:Resultat:new" }

resultat_create:
    pattern:  /create
    defaults: { _controller: "KemistraMainBundle:Resultat:create" }
    requirements: { _method: post }

resultat_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KemistraMainBundle:Resultat:edit" }

resultat_update:
    pattern:  /{id}/update
    defaults: { _controller: "KemistraMainBundle:Resultat:update" }
    requirements: { _method: post|put }

resultat_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KemistraMainBundle:Resultat:delete" }
    requirements: { _method: post|delete }
