typeconsommable:
    pattern:  /
    defaults: { _controller: "KemistraMainBundle:TypeConsommable:index" }

typeconsommable_show:
    pattern:  /{id}/show
    defaults: { _controller: "KemistraMainBundle:TypeConsommable:show" }

typeconsommable_new:
    pattern:  /new
    defaults: { _controller: "KemistraMainBundle:TypeConsommable:new" }

typeconsommable_create:
    pattern:  /create
    defaults: { _controller: "KemistraMainBundle:TypeConsommable:create" }
    requirements: { _method: post }

typeconsommable_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KemistraMainBundle:TypeConsommable:edit" }

typeconsommable_update:
    pattern:  /{id}/update
    defaults: { _controller: "KemistraMainBundle:TypeConsommable:update" }
    requirements: { _method: post|put }

typeconsommable_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KemistraMainBundle:TypeConsommable:delete" }
    requirements: { _method: post|delete }
